# Generated by Django 3.0.5 on 2020-04-30 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20)),
                ('c_price', models.CharField(blank=True, max_length=10, null=True)),
                ('c_mom', models.CharField(blank=True, max_length=10, null=True)),
                ('c_yoy', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'city',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'province',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UrbanArea',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(blank=True, max_length=30, null=True)),
                ('u_price', models.CharField(blank=True, max_length=10, null=True)),
                ('u_mom', models.CharField(blank=True, max_length=10, null=True)),
                ('u_yoy', models.CharField(blank=True, max_length=10, null=True)),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='house.City')),
            ],
            options={
                'db_table': 'urban_area',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='house.Province'),
        ),
    ]
