# Generated by Django 3.0.5 on 2020-04-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20200430_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={},
        ),
        migrations.AlterModelOptions(
            name='urbanarea',
            options={},
        ),
        migrations.AlterModelTable(
            name='city',
            table=None,
        ),
        migrations.AlterModelTable(
            name='province',
            table=None,
        ),
        migrations.AlterModelTable(
            name='urbanarea',
            table=None,
        ),
    ]
